In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## Question 1

In [3]:
# Question 1: Given a list of tuples, find the number of occurrences of each tuple in the list.


def get_occ_tuple(lis):
  d = {}
  for item in lis:
      if not d.get(item):
          d[item] = 0
      d[item] += 1
  return d


lis = [(1, 2, 3, 4, 5), (1, 2), (1, 2), (1, 2), (1, 2), (2, 3, 4), (3, 4)]
print(get_occ_tuple(lis))

{(1, 2, 3, 4, 5): 1, (1, 2): 4, (2, 3, 4): 1, (3, 4): 1}

## Question 2

In [4]:
# Question 2: Create a list of 10 random numbers between 1-100. Create a balanced BST (Binary search tree) from this array

import random

class Node:
    def __init__(self, value):
        self.value = value
        self.left = None
        self.right = None
        
class BST:
    def __init__(self, array: list) -> None:
        self.array = array
        self.n = len(self.array)
        self.root = None
        
    def sort(self) -> None:
        # Bubble Sort
        n = len(self.array)
    
        for i in range(n):
            for j in range(n-i-1):
                if self.array[j] > self.array[j+1]:
                    self.array[j], self.array[j+1] = self.array[j+1], self.array[j]
    
    def build_bst(self, array: list) -> Node:
        # Build the Balanced BST
      
        if not array:
            return None

        mid = (len(array))//2
        root = Node(array[mid])
        root.left = self.build_bst(array[:mid])
        root.right = self.build_bst(array[mid+1:])
        
        return root
    
    def print_preorder_bst(self, node: Node) -> None:
        # Pre-Order
        if not node:
            return
        
        print(node.value, end='|') 
        self.print_preorder_bst(node.left)
        self.print_preorder_bst(node.right)
        
        return
    
    def direction(self) -> None:
        self.sort()
        self.root = self.build_bst(self.array)
        self.print_preorder_bst(self.root)


# Random List Generation
lis = random.sample(range(1, 100), 10)
print(f"Randomly generated list : {lis}")

obj = BST(lis)
obj.direction()

# Printing in 2D
space_count = 8
def print_in_2d(root: Node, space: int):
    if root == None:
        return
    space += space_count
    
    print_in_2d(root.right, space)
    print()
    print(" "*(space - space_count), end="") # 
    print(root.value)  
    print_in_2d(root.left, space)

print_in_2d(obj.root, 0)

Randomly generated list : [24, 69, 90, 75, 28, 96, 43, 26, 91, 10]
69|26|24|10|43|28|91|90|75|96|
                96

        91

                90

                        75

69

                43

                        28

        26

                24

                        10

## Question 3

In [5]:
# Question 3: Given the following dictionary:Create a list of all the keys of the dictionary, which can be formed from the values present in the dictionary.


ldict = {
    'black': 'r',
    'hero': 'e',
    'go': 'g',
    'clue': 'i',
    'mean': 'q',
    'groan': 'o',
    'sin': 'p',
    'pint': 'u',
    'tone': 'n',
    'graze': 's',
    'sea': 't',
    'plant': 'a'
}


new_dict = {}
words_cant_be_made = []
words_can_be_made = set(ldict.keys())

for word in ldict.keys():
    for letter in word:
        if not new_dict.get(letter):
            new_dict[letter] = []
        new_dict[letter].append(word)
print("\nFirst Step")
print(new_dict)
for item in ldict.values():
    if new_dict.get(item):
        new_dict.pop(item)
print("\nSecond Step")
print(new_dict)
        
words_cant_be_made = []
for val in new_dict.values():
    words_cant_be_made.extend(val)
words_cant_be_made = set(words_cant_be_made)
words_can_be_made = list(words_can_be_made - words_cant_be_made)
print(f"\nWords that can be made : {words_can_be_made}")

First Step
{'b': ['black'], 'l': ['black', 'clue', 'plant'], 'a': ['black', 'mean', 'groan', 'graze', 'sea', 'plant'], 'c': ['black', 'clue'], 'k': ['black'], 'h': ['hero'], 'e': ['hero', 'clue', 'mean', 'tone', 'graze', 'sea'], 'r': ['hero', 'groan', 'graze'], 'o': ['hero', 'go', 'groan', 'tone'], 'g': ['go', 'groan', 'graze'], 'u': ['clue'], 'm': ['mean'], 'n': ['mean', 'groan', 'sin', 'pint', 'tone', 'plant'], 's': ['sin', 'sea'], 'i': ['sin', 'pint'], 'p': ['pint', 'plant'], 't': ['pint', 'tone', 'plant'], 'z': ['graze']}

Second Step
{'b': ['black'], 'l': ['black', 'clue', 'plant'], 'c': ['black', 'clue'], 'k': ['black'], 'h': ['hero'], 'm': ['mean'], 'z': ['graze']}

Words that can be made : ['sin', 'tone', 'go', 'groan', 'pint', 'sea']

## Question 4

In [6]:
""" 
Question 4: Given the following list of tuples,

a.    sort the list by 1st item in the tuple in ascending order

b.    Sort the list by 2nd item in the tuple in ascending order

c.     Repeat a, b using descending order

listA = [(1,2), (4,3), (2,10), (12, 5), (6, 7), (9,11), (15, 4)]
"""


def sort_tuple_asc(tup, choice):
    n = len(tup)
    for i in range(n):
        for j in range(n-i-1):
            if tup[j][choice] > tup[j + 1][choice]:
                tup[j], tup[j + 1] = tup[j + 1], tup[j]
    return tup

def sort_tuple_desc(tup, choice):
    n = len(tup)
    for i in range(n):
        for j in range(n-i-1):
            if tup[j][choice] < tup[j + 1][choice]:
                tup[j], tup[j + 1] = tup[j + 1], tup[j]
    return tup


listA = [(1,2), (4,3), (2,10), (12, 5), (6, 7), (9,11), (15, 4)]

def list_sort(listA):
  for i in range(2):
    choice = i
    print(f"\nAscending : {choice} element")
    print(sort_tuple_asc(listA, choice))
    print(f"\nDescending : {choice} element")
    print(sort_tuple_desc(listA, choice))

list_sort(listA)

Ascending : 0 element
[(1, 2), (2, 10), (4, 3), (6, 7), (9, 11), (12, 5), (15, 4)]

Descending : 0 element
[(15, 4), (12, 5), (9, 11), (6, 7), (4, 3), (2, 10), (1, 2)]

Ascending : 1 element
[(1, 2), (4, 3), (15, 4), (12, 5), (6, 7), (2, 10), (9, 11)]

Descending : 1 element
[(9, 11), (2, 10), (6, 7), (12, 5), (15, 4), (4, 3), (1, 2)]

## Question 5

In [7]:
# Question 5: What do you mean by a mutable and immutable object. Are string, list, tuple, dictionary mutable type objects or immutable objects.
"""
Mutable : Object can be changed after it is created.
Immutable : Object can't be changed after it is created.

String : Immutable
List : Mutable
Tuple : Immutable
Dictionary : Mutable

"""

"\nMutable : Object can be changed after it is created.\nImmutable : Object can't be changed after it is created.\n\nString : Immutable\nList : Mutable\nTuple : Immutable\nDictionary : Mutable\n\n"

## Question 6

In [8]:
"""
Question 6: Learn The usage of Pandas and Numpy:

1)    Write the command to find unique values in education.
2)    Command to find the number of customers subscribed and not subscribed.
3)    Find the mean values of all the independent variables for every ‘y’ (outcome variable)
4)    What is the mean age for every marital status
5)    Check for null values
6)    Find the descriptive statistics for each column
7)    Use pd.query(), iloc, loc and range subsetting to extract insights from the data. 
      You will be evaluated on the quality of your queries and the rationale behind selecting them. 
      You can extract upto five (5) separate insights from the data.
"""

import pandas as pd
import numpy as np

pd.options.display.max_columns = 30

In [9]:
data = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/prereq/banking.csv")
print(f"Shape : {data.shape}")
data.head()

Shape : (41188, 21)

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,duration,campaign,pdays,previous,poutcome,emp_var_rate,cons_price_idx,cons_conf_idx,euribor3m,nr_employed,y
0,44,blue-collar,married,basic.4y,unknown,yes,no,cellular,aug,thu,210,1,999,0,nonexistent,1.4,93.444,-36.1,4.963,5228.1,0
1,53,technician,married,unknown,no,no,no,cellular,nov,fri,138,1,999,0,nonexistent,-0.1,93.200,-42.0,4.021,5195.8,0
2,28,management,single,university.degree,no,yes,no,cellular,jun,thu,339,3,6,2,success,-1.7,94.055,-39.8,0.729,4991.6,1
3,39,services,married,high.school,no,no,no,cellular,apr,fri,185,2,999,0,nonexistent,-1.8,93.075,-47.1,1.405,5099.1,0
4,55,retired,married,basic.4y,no,yes,no,cellular,aug,fri,137,1,3,1,success,-2.9,92.201,-31.4,0.869,5076.2,1

In [10]:
# 1. Write the command to find unique values in education.
data['education'].unique()

array(['basic.4y', 'unknown', 'university.degree', 'high.school',
       'basic.9y', 'professional.course', 'basic.6y', 'illiterate'],
      dtype=object)

In [11]:
# 2. Command to find the number of customers subscribed and not subscribed.
data['y'].value_counts()

0    36548
1     4640
Name: y, dtype: int64

In [12]:
# 3. Find the mean values of all the independent variables for every ‘y’ (outcome variable)
data.groupby(['y']).mean()

,age,duration,campaign,pdays,previous,emp_var_rate,cons_price_idx,cons_conf_idx,euribor3m,nr_employed
y,,,,,,,,,,
0,39.911185,220.844807,2.633085,984.113878,0.132374,0.248875,93.603757,-40.593097,3.811491,5176.166600
1,40.913147,553.191164,2.051724,792.035560,0.492672,-1.233448,93.354386,-39.789784,2.123135,5095.115991

In [13]:
# 4. What is the mean age for every marital status
data.groupby(['marital'])['age'].mean()

marital
divorced    44.899393
married     42.307165
single      33.158714
unknown     40.275000
Name: age, dtype: float64

In [14]:
# 5. Check for null values
data.isnull().sum()

age               0
job               0
marital           0
education         0
default           0
housing           0
loan              0
contact           0
month             0
day_of_week       0
duration          0
campaign          0
pdays             0
previous          0
poutcome          0
emp_var_rate      0
cons_price_idx    0
cons_conf_idx     0
euribor3m         0
nr_employed       0
y                 0
dtype: int64

In [15]:
# 6. Find the descriptive statistics for each column
data.describe(include='all')

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,duration,campaign,pdays,previous,poutcome,emp_var_rate,cons_price_idx,cons_conf_idx,euribor3m,nr_employed,y
count,41188.00000,41188,41188,41188,41188,41188,41188,41188,41188,41188,41188.000000,41188.000000,41188.000000,41188.000000,41188,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000
unique,NaN,12,4,8,3,3,3,2,10,5,NaN,NaN,NaN,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,admin.,married,university.degree,no,yes,no,cellular,may,thu,NaN,NaN,NaN,NaN,nonexistent,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,10422,24928,12168,32588,21576,33950,26144,13769,8623,NaN,NaN,NaN,NaN,35563,NaN,NaN,NaN,NaN,NaN,NaN
mean,40.02406,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,258.285010,2.567593,962.475454,0.172963,NaN,0.081886,93.575664,-40.502600,3.621291,5167.035911,0.112654
std,10.42125,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,259.279249,2.770014,186.910907,0.494901,NaN,1.570960,0.578840,4.628198,1.734447,72.251528,0.316173
min,17.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,1.000000,0.000000,0.000000,NaN,-3.400000,92.201000,-50.800000,0.634000,4963.600000,0.000000
25%,32.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102.000000,1.000000,999.000000,0.000000,NaN,-1.800000,93.075000,-42.700000,1.344000,5099.100000,0.000000
50%,38.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,180.000000,2.000000,999.000000,0.000000,NaN,1.100000,93.749000,-41.800000,4.857000,5191.000000,0.000000
75%,47.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,319.000000,3.000000,999.000000,0.000000,NaN,1.400000,93.994000,-36.400000,4.961000,5228.100000,0.000000
max,98.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4918.000000,56.000000,999.000000,7.000000,NaN,1.400000,94.767000,-26.900000,5.045000,5228.100000,1.000000

In [16]:
"""
  7. Use pd.query(), iloc, loc and range subsetting to extract insights from the data. 
  You will be evaluated on the quality of your queries and the rationale behind selecting them. 
  You can extract upto five (5) separate insights from the data.
"""

'\n  7. Use pd.query(), iloc, loc and range subsetting to extract insights from the data. \n  You will be evaluated on the quality of your queries and the rationale behind selecting them. \n  You can extract upto five (5) separate insights from the data.\n'

In [17]:
bank = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/prereq/banking.csv')

In [18]:
bank.head()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,duration,campaign,pdays,previous,poutcome,emp_var_rate,cons_price_idx,cons_conf_idx,euribor3m,nr_employed,y
0,44,blue-collar,married,basic.4y,unknown,yes,no,cellular,aug,thu,210,1,999,0,nonexistent,1.4,93.444,-36.1,4.963,5228.1,0
1,53,technician,married,unknown,no,no,no,cellular,nov,fri,138,1,999,0,nonexistent,-0.1,93.200,-42.0,4.021,5195.8,0
2,28,management,single,university.degree,no,yes,no,cellular,jun,thu,339,3,6,2,success,-1.7,94.055,-39.8,0.729,4991.6,1
3,39,services,married,high.school,no,no,no,cellular,apr,fri,185,2,999,0,nonexistent,-1.8,93.075,-47.1,1.405,5099.1,0
4,55,retired,married,basic.4y,no,yes,no,cellular,aug,fri,137,1,3,1,success,-2.9,92.201,-31.4,0.869,5076.2,1

In [22]:
## Find a person who is working as a technician and aged between 40-50 and subscribes to the bank

q1 = bank.query(
    'job == "technician"  and age >=40 and age<=50 and y == 1'
)

In [23]:
q1

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,duration,campaign,pdays,previous,poutcome,emp_var_rate,cons_price_idx,cons_conf_idx,euribor3m,nr_employed,y
725,46,technician,married,university.degree,unknown,no,yes,telephone,jun,thu,993,6,999,0,nonexistent,1.4,94.465,-41.8,4.958,5228.1,1
753,49,technician,divorced,professional.course,no,yes,no,cellular,jul,mon,253,3,15,1,success,-1.7,94.215,-40.3,0.870,4991.6,1
809,48,technician,married,unknown,no,yes,no,cellular,jul,mon,1096,2,999,0,nonexistent,1.4,93.918,-42.7,4.962,5228.1,1
821,45,technician,married,university.degree,no,yes,yes,telephone,may,tue,845,1,999,0,nonexistent,1.1,93.994,-36.4,4.856,5191.0,1
2044,49,technician,married,professional.course,no,no,no,telephone,may,fri,736,2,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39244,44,technician,married,university.degree,no,no,no,cellular,jun,wed,874,2,999,1,failure,-1.7,94.055,-39.8,0.715,4991.6,1
39517,40,technician,divorced,university.degree,no,yes,no,cellular,apr,thu,335,1,999,0,nonexistent,-1.8,93.075,-47.1,1.365,5099.1,1
39545,46,technician,divorced,university.degree,unknown,yes,no,telephone,jul,fri,1946,4,999,0,nonexistent,1.4,93.918,-42.7,4.962,5228.1,1
40508,50,technician,married,professional.course,no,unknown,unknown,cellular,oct,fri,447,1,8,2,failure,-3.4,92.431,-26.9,0.739,5017.5,1
40751,48,technician,married,professional.course,no,yes,no,cellular,aug,fri,336,8,999,0,nonexistent,1.4,93.444,-36.1,4.964,5228.1,1

In [29]:
## retrieve the data whose age between 20-30 and has a loan and subscribes to the bank
q2 = bank.query(
    'age >= 20 and age<=30 and loan == "yes" and y == 1'
)
q2

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,duration,campaign,pdays,previous,poutcome,emp_var_rate,cons_price_idx,cons_conf_idx,euribor3m,nr_employed,y
404,30,technician,married,university.degree,no,yes,yes,cellular,jul,mon,204,4,999,0,nonexistent,-1.7,94.215,-40.3,0.870,4991.6,1
436,29,admin.,single,university.degree,no,yes,yes,cellular,nov,thu,736,1,999,0,nonexistent,-0.1,93.200,-42.0,4.076,5195.8,1
1095,29,student,single,high.school,no,no,yes,telephone,may,mon,630,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,1
1976,29,admin.,single,university.degree,no,no,yes,cellular,jul,thu,582,2,999,0,nonexistent,1.4,93.918,-42.7,4.958,5228.1,1
2365,27,blue-collar,single,basic.9y,no,yes,yes,cellular,may,thu,224,4,999,0,nonexistent,-1.8,92.893,-46.2,1.266,5099.1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39987,29,management,single,basic.9y,no,no,yes,cellular,jul,fri,968,1,999,0,nonexistent,1.4,93.918,-42.7,4.957,5228.1,1
40384,30,blue-collar,married,basic.6y,no,yes,yes,cellular,jul,wed,1018,2,999,0,nonexistent,1.4,93.918,-42.7,4.957,5228.1,1
40571,25,self-employed,divorced,university.degree,no,no,yes,cellular,apr,mon,163,1,999,0,nonexistent,-1.8,93.075,-47.1,1.405,5099.1,1
40693,29,admin.,single,university.degree,no,yes,yes,cellular,aug,thu,254,3,3,1,success,-2.9,92.201,-31.4,0.873,5076.2,1
41078,20,student,single,basic.4y,no,yes,yes,cellular,apr,tue,278,4,6,1,success,-1.8,93.749,-34.6,0.644,5008.7,1

In [30]:
bank['job'].unique()

array(['blue-collar', 'technician', 'management', 'services', 'retired',
       'admin.', 'housemaid', 'unemployed', 'entrepreneur',
       'self-employed', 'unknown', 'student'], dtype=object)

In [31]:
##Retrieve a data whose job is technician or management and has not subscribed to the bank
q3 = bank.query(
    'job == "technician" or job == "management" and y == 0'
)
q3

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,duration,campaign,pdays,previous,poutcome,emp_var_rate,cons_price_idx,cons_conf_idx,euribor3m,nr_employed,y
1,53,technician,married,unknown,no,no,no,cellular,nov,fri,138,1,999,0,nonexistent,-0.1,93.200,-42.0,4.021,5195.8,0
5,30,management,divorced,basic.4y,no,yes,no,cellular,jul,tue,68,8,999,0,nonexistent,1.4,93.918,-42.7,4.961,5228.1,0
11,41,management,married,university.degree,no,yes,no,cellular,aug,thu,789,1,999,0,nonexistent,1.4,93.444,-36.1,4.964,5228.1,0
23,32,technician,single,professional.course,no,no,no,cellular,jul,thu,35,1,999,0,nonexistent,1.4,93.918,-42.7,4.968,5228.1,0
26,49,technician,divorced,unknown,no,yes,yes,cellular,oct,thu,81,1,999,0,nonexistent,-3.4,92.431,-26.9,0.754,5017.5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41169,46,technician,married,basic.9y,no,no,no,cellular,nov,tue,530,1,999,0,nonexistent,-0.1,93.200,-42.0,4.153,5195.8,0
41170,32,technician,single,university.degree,no,yes,yes,cellular,aug,thu,195,3,999,0,nonexistent,1.4,93.444,-36.1,4.962,5228.1,0
41178,35,technician,married,high.school,no,no,no,telephone,aug,fri,243,1,999,0,nonexistent,1.4,93.444,-36.1,4.966,5228.1,1
41179,29,technician,single,basic.9y,no,yes,no,cellular,may,mon,214,1,999,0,nonexistent,-1.8,92.893,-46.2,1.299,5099.1,0
41186,48,technician,married,professional.course,no,no,yes,telephone,oct,tue,200,2,999,0,nonexistent,-3.4,92.431,-26.9,0.742,5017.5,0

In [35]:
##retrieve data whose marital status is not single and whose age is less than 40 and studying in university degree
q4 = bank.loc[(bank['marital']!='single') & (bank['age']< 40) & (bank['education']=='university.degree')]

q4

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,duration,campaign,pdays,previous,poutcome,emp_var_rate,cons_price_idx,cons_conf_idx,euribor3m,nr_employed,y
8,36,admin.,married,university.degree,no,no,no,cellular,jun,mon,174,1,3,1,success,-2.9,92.963,-40.8,1.266,5076.2,1
54,39,management,married,university.degree,no,yes,no,telephone,may,wed,68,1,999,0,nonexistent,1.1,93.994,-36.4,4.859,5191.0,0
62,30,management,married,university.degree,no,no,no,cellular,mar,mon,116,1,999,0,nonexistent,-1.8,92.843,-50.0,1.811,5099.1,1
63,37,admin.,married,university.degree,no,yes,no,cellular,nov,fri,450,1,999,0,nonexistent,-0.1,93.200,-42.0,4.021,5195.8,0
72,33,entrepreneur,married,university.degree,no,no,no,cellular,nov,thu,55,1,999,0,nonexistent,-0.1,93.200,-42.0,4.076,5195.8,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41109,36,admin.,married,university.degree,no,yes,no,cellular,may,fri,334,3,999,0,nonexistent,-1.8,92.893,-46.2,1.313,5099.1,0
41111,30,technician,married,university.degree,no,yes,no,cellular,dec,thu,244,2,6,1,success,-3.0,92.713,-33.0,0.720,5023.5,1
41128,32,self-employed,married,university.degree,no,yes,no,cellular,jul,wed,181,1,999,0,nonexistent,1.4,93.918,-42.7,4.963,5228.1,0
41143,32,admin.,married,university.degree,no,no,no,cellular,nov,thu,18,6,999,0,nonexistent,-0.1,93.200,-42.0,4.076,5195.8,0
41181,39,admin.,married,university.degree,no,no,no,cellular,nov,tue,123,2,999,0,nonexistent,-0.1,93.200,-42.0,4.153,5195.8,0

In [39]:
##Retrieve the data where education is highschool  and who has a loan and who has not subscribed to the bank and aged below 25

q5 = bank.loc[(bank['education'] == 'high.school') & (bank['loan'] == 'yes') & (bank['y'] == 0) & (bank['age'] < 25)]
q5

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,duration,campaign,pdays,previous,poutcome,emp_var_rate,cons_price_idx,cons_conf_idx,euribor3m,nr_employed,y
57,24,admin.,married,high.school,no,no,yes,telephone,may,mon,61,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,0
1171,24,admin.,single,high.school,no,no,yes,cellular,jul,tue,210,5,999,0,nonexistent,1.4,93.918,-42.7,4.961,5228.1,0
1306,24,student,single,high.school,unknown,yes,yes,telephone,may,fri,103,7,999,0,nonexistent,1.1,93.994,-36.4,4.859,5191.0,0
2658,22,admin.,married,high.school,no,yes,yes,cellular,apr,fri,156,2,999,0,nonexistent,-1.8,93.075,-47.1,1.405,5099.1,0
4133,24,services,single,high.school,no,yes,yes,telephone,may,thu,198,1,999,0,nonexistent,1.1,93.994,-36.4,4.855,5191.0,0
6153,22,student,single,high.school,no,yes,yes,cellular,jun,thu,221,1,999,1,failure,-2.9,92.963,-40.8,1.260,5076.2,0
6659,20,entrepreneur,single,high.school,no,no,yes,telephone,may,wed,680,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,0
7021,24,admin.,single,high.school,no,no,yes,cellular,mar,thu,181,1,999,0,nonexistent,-1.8,92.843,-50.0,1.584,5099.1,0
7087,24,admin.,single,high.school,no,yes,yes,cellular,jul,thu,109,5,999,0,nonexistent,1.4,93.918,-42.7,4.968,5228.1,0
8635,23,admin.,married,high.school,no,no,yes,cellular,may,thu,7,5,999,1,failure,-1.8,92.893,-46.2,1.266,5099.1,0
9115,24,services,married,high.school,no,no,yes,telephone,may,fri,241,1,999,0,nonexistent,1.1,93.994,-36.4,4.859,5191.0,0
9679,20,student,single,high.school,no,yes,yes,cellular,jun,wed,74,2,999,1,failure,-2.9,92.963,-40.8,1.260,5076.2,0
10371,21,student,single,high.school,no,yes,yes,cellular,aug,tue,220,1,999,0,nonexistent,-2.9,92.201,-31.4,0.884,5076.2,0
10974,22,services,single,high.school,no,yes,yes,cellular,jun,mon,181,1,999,0,nonexistent,-2.9,92.963,-40.8,1.260,5076.2,0
11619,22,student,single,high.school,no,yes,yes,telephone,may,thu,382,3,999,1,failure,-1.8,92.893,-46.2,1.266,5099.1,0
11775,20,student,single,high.school,no,no,yes,cellular,oct,mon,169,1,999,0,nonexistent,-3.4,92.431,-26.9,0.739,5017.5,0
11844,24,student,single,high.school,no,yes,yes,cellular,jun,thu,344,1,999,0,nonexistent,-1.7,94.055,-39.8,0.729,4991.6,0
12940,22,housemaid,single,high.school,no,yes,yes,cellular,jul,mon,767,12,999,0,nonexistent,1.4,93.918,-42.7,4.962,5228.1,0
14001,24,student,single,high.school,no,no,yes,cellular,apr,thu,157,1,999,0,nonexistent,-1.8,93.075,-47.1,1.365,5099.1,0
14733,24,admin.,single,high.school,no,yes,yes,cellular,jul,wed,100,3,999,0,nonexistent,1.4,93.918,-42.7,4.963,5228.1,0
16267,24,student,single,high.school,no,yes,yes,cellular,may,wed,66,1,999,1,failure,-1.8,92.893,-46.2,1.281,5099.1,0
17040,24,admin.,married,high.school,no,no,yes,telephone,jun,mon,1330,6,999,0,nonexistent,1.4,94.465,-41.8,4.865,5228.1,0
18799,24,services,single,high.school,no,no,yes,telephone,may,fri,134,1,999,0,nonexistent,1.1,93.994,-36.4,4.855,5191.0,0
19366,24,admin.,single,high.school,no,yes,yes,telephone,jul,thu,354,1,999,0,nonexistent,1.4,93.918,-42.7,4.966,5228.1,0
19426,24,student,single,high.school,no,yes,yes,cellular,nov,mon,106,1,999,0,nonexistent,-1.1,94.767,-50.8,1.050,4963.6,0
19877,24,services,single,high.school,no,no,yes,cellular,apr,fri,1426,2,999,1,failure,-1.8,93.075,-47.1,1.405,5099.1,0
21304,24,student,single,high.school,no,yes,yes,cellular,aug,fri,44,1,999,1,failure,-2.9,92.201,-31.4,0.849,5076.2,0
21405,24,services,single,high.school,no,yes,yes,telephone,jun,mon,183,2,999,0,nonexistent,1.4,94.465,-41.8,4.961,5228.1,0
21742,24,services,single,high.school,no,no,yes,cellular,may,thu,91,1,999,1,failure,-1.8,92.893,-46.2,1.266,5099.1,0
22117,22,admin.,married,high.school,no,no,yes,cellular,apr,fri,108,2,999,1,failure,-1.8,93.075,-47.1,1.405,5099.1,0
22797,20,student,single,high.school,no,yes,yes,cellular,jul,tue,136,4,999,0,nonexistent,1.4,93.918,-42.7,4.961,5228.1,0
23036,21,student,single,high.school,no,no,yes,cellular,oct,mon,238,1,999,0,nonexistent,-3.4,92.431,-26.9,0.739,5017.5,0
23390,23,blue-collar,married,high.school,no,no,yes,telephone,jun,thu,173,3,999,0,nonexistent,1.4,94.465,-41.8,4.866,5228.1,0
23405,22,student,single,high.school,no,no,yes,cellular,jul,wed,349,1,999,0,nonexistent,1.4,93.918,-42.7,4.962,5228.1,0
24398,19,student,single,high.school,unknown,no,yes,cellular,may,tue,106,4,999,0,nonexistent,-1.8,92.893,-46.2,1.344,5099.1,0
24970,24,student,single,high.school,no,yes,yes,cellular,aug,fri,298,1,999,0,nonexistent,-2.9,92.201,-31.4,0.849,5076.2,0
26072,18,student,single,high.school,no,yes,yes,cellular,mar,tue,103,1,999,0,nonexistent,-1.8,92.843,-50.0,1.687,5099.1,0
27861,21,services,single,high.school,no,yes,yes,cellular,apr,thu,820,2,999,0,nonexistent,-1.8,93.075,-47.1,1.435,5099.1,0
32496,24,admin.,single,high.school,unknown,yes,yes,cellular,jul,thu,493,1,999,0,nonexistent,1.4,93.918,-42.7,4.958,5228.1,0
35113,22,student,single,high.school,no,no,yes,cellular,jul,fri,154,2,999,0,nonexistent,1.4,93.918,-42.7,4.957,5228.1,0
35850,24,services,single,high.school,no,yes,yes,cellular,may,fri,20,5,999,0,nonexistent,-1.8,92.893,-46.2,1.250,5099.1,0
36085,21,admin.,single,high.school,no,no,yes,cellular,may,thu,240,1,999,0,nonexistent,-1.8,92.893,-46.2,1.266,5099.1,0
36898,21,unemployed,married,high.school,no,yes,yes,cellular,jul,thu,85,3,999,0,nonexistent,1.4,93.918,-42.7,4.962,5228.1,0
37816,24,services,single,high.school,no,yes,yes,cellular,may,fri,69,2,999,2,failure,-1.8,92.893,-46.2,1.250,5099.1,0
39048,24,admin.,single,high.school,no,yes,yes,telephone,jul,tue,162,1,999,0,nonexistent,1.4,93.918,-42.7,4.961,5228.1,0
39190,24,services,single,high.school,no,yes,yes,cellular,may,mon,590,1,999,1,failure,-1.8,92.893,-46.2,1.299,5099.1,0
40406,24,student,single,high.school,no,yes,yes,cellular,jul,tue,316,3,999,1,failure,-1.7,94.215,-40.3,0.835,4991.6,0
40496,23,services,single,high.school,no,yes,yes,cellular,jul,mon,129,2,999,0,nonexistent,1.4,93.918,-42.7,4.960,5228.1,0
40932,23,services,single,high.school,no,no,yes,cellular,jul,wed,207,1,999,0,nonexistent,1.4,93.918,-42.7,4.963,5228.1,0